### ISSUE TITLE
Plugin crashes with TypeError in Yarn v3

### ISSUE THREAD

**Issue by AlCalzone** [Dcard/yarn-plugins#11]
Stack:
```
$ yarn changed list
➤ YN0001: TypeError: Cannot read property 'length' of undefined
    at C:\Repositories\node-zwave-js\.yarn\plugins\@yarnpkg\plugin-changed.cjs:5:1737
    at Array.filter (<anonymous>)
    at listWorkspaces (C:\Repositories\node-zwave-js\.yarn\plugins\@yarnpkg\plugin-changed.cjs:5:1656)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Repositories\node-zwave-js\.yarn\plugins\@yarnpkg\plugin-changed.cjs:5:2770
    at async Function.start (C:\Repositories\node-zwave-js\.yarn\releases\yarn-3.0.0-rc.6.cjs:273:2287)
    at async l.execute (C:\Repositories\node-zwave-js\.yarn\plugins\@yarnpkg\plugin-changed.cjs:5:2665)
    at async l.validateAndExecute (C:\Repositories\node-zwave-js\.yarn\releases\yarn-3.0.0-rc.6.cjs:197:620)
    at async _n.run (C:\Repositories\node-zwave-js\.yarn\releases\yarn-3.0.0-rc.6.cjs:209:1846)
    at async _n.runExit (C:\Repositories\node-zwave-js\.yarn\releases\yarn-3.0.0-rc.6.cjs:209:2013)
```

**Comment by Piero87** [comment]
same error, how have you fix it?

**Comment by AlCalzone** [comment]
I went back to `lerna` for now.
